#!/usr/bin/env bash
# This file is auto-generated by @lark-apaas/fullstack-cli
set -euo pipefail

ROOT_DIR="$(pwd)"
OUT_DIR="$ROOT_DIR/dist/server"

# 记录总开始时间
TOTAL_START=$(node -e "console.log(Date.now())")

# 打印耗时的辅助函数
print_time() {
  local start=$1
  local end=$(node -e "console.log(Date.now())")
  local elapsed=$((end - start))
  local seconds=$((elapsed / 1000))
  local ms=$((elapsed % 1000))
  echo "   ⏱️  耗时: ${seconds}.$(printf "%03d" $ms)s"
}

# ==================== 步骤 0 ====================
echo "🗑️  [0/5] 安装插件"
STEP_START=$(node -e "console.log(Date.now())")
npx fullstack-cli action-plugin init
print_time $STEP_START
echo ""

# ==================== 步骤 1 ====================
echo "📝 [1/5] 更新 openapi 代码"
STEP_START=$(node -e "console.log(Date.now())")
npm run gen:openapi
print_time $STEP_START
echo ""

# ==================== 步骤 2 ====================
echo "🗑️  [2/5] 清理 dist 目录"
STEP_START=$(node -e "console.log(Date.now())")
rm -rf "$ROOT_DIR/dist"
print_time $STEP_START
echo ""

# ==================== 步骤 3 ====================
echo "🔨 [3/5] 并行构建 server 和 client"
STEP_START=$(node -e "console.log(Date.now())")

# 并行构建
echo "   ├─ 启动 server 构建..."
npm run build:server > /tmp/build-server.log 2>&1 &
SERVER_PID=$!

echo "   ├─ 启动 client 构建..."
npm run build:client > /tmp/build-client.log 2>&1 &
CLIENT_PID=$!

# 等待两个构建完成
SERVER_EXIT=0
CLIENT_EXIT=0

wait $SERVER_PID || SERVER_EXIT=$?
wait $CLIENT_PID || CLIENT_EXIT=$?

# 检查构建结果
if [ $SERVER_EXIT -ne 0 ]; then
  echo "   ❌ Server 构建失败"
  cat /tmp/build-server.log
  exit 1
fi

if [ $CLIENT_EXIT -ne 0 ]; then
  echo "   ❌ Client 构建失败"
  cat /tmp/build-client.log
  exit 1
fi

echo "   ✅ Server 构建完成"
echo "   ✅ Client 构建完成"
print_time $STEP_START
echo ""

# ==================== 步骤 4 ====================
echo "📦 [4/5] 准备 server 依赖产物"
STEP_START=$(node -e "console.log(Date.now())")

mkdir -p "$OUT_DIR/dist/client"

# public 先进（server setBaseViewsDir + nestjs-core 中间件同源 serve）
if [ -d "$ROOT_DIR/client/public" ]; then
  cp -R "$ROOT_DIR/client/public/." "$OUT_DIR/dist/client/"
fi

# 构建产物 HTML 随后拷，覆盖 public 里的同名文件（保证入口页是构建版，不被 public 静默覆盖）
cp "$ROOT_DIR/dist/client/"*.html "$OUT_DIR/dist/client/" || true

# 拷贝 run.sh 文件
cp "$ROOT_DIR/scripts/run.sh" "$OUT_DIR/"

# 清理无用文件
rm -rf "$ROOT_DIR/dist/scripts"
rm -rf "$ROOT_DIR/dist/tsconfig.node.tsbuildinfo"

print_time $STEP_START
echo ""

# ==================== 步骤 5 ====================
echo "✂️  [5/5] 智能依赖裁剪"
STEP_START=$(node -e "console.log(Date.now())")

# 分析实际依赖、复制并裁剪 node_modules、生成精简的 package.json
node "$ROOT_DIR/scripts/prune-smart.js"

print_time $STEP_START
echo ""

# 总耗时
echo "构建完成"
print_time $TOTAL_START

# 输出产物信息
DIST_SIZE=$(du -sh "$OUT_DIR" | cut -f1)
NODE_MODULES_SIZE=$(du -sh "$OUT_DIR/node_modules" | cut -f1)
echo ""
echo "📊 构建产物统计:"
echo "   总大小:        $DIST_SIZE"
echo "   node_modules: $NODE_MODULES_SIZE"
echo ""
